version: "3.8"

services:
    postgres:
        image: postgres:13-alpine
        restart: on-failure
        environment:
            POSTGRES_DB: symfony
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            PGDATA: /var/lib/postgresql/data
        volumes:
            - db-data:/var/lib/postgresql/data:rw
        ports:
            - "5432:5432"
        networks:
            - dev

    php:
        build:
            context: .
            target: sf5_php
        image: rafiousitou/sf5-php-8.0:dev
        restart: on-failure
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
            XDEBUG_CONFIG: remote_host=host.docker.internal
            PHP_IDE_CONFIG: serverName=localhost
        volumes:
            - ./:/var/www/app:rw,cached
        depends_on:
            - postgres
        networks:
            - dev

    nginx:
        build:
            context: .
            target: sf5_nginx
        image: rafiousitou/sf5-nginx-1.19:dev
        restart: on-failure
        ports:
            - "8080:80"
        volumes:
            - ./public:/var/www/app/public:ro
        depends_on:
            - php
        networks:
            - dev

networks:
    dev:

volumes:
    db-data: